WebApp/GestordePacientes/Controllers/CitasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GestordePacientes.Controllers
{
    public class CitasController : Controller
    {
        [Authorize(Roles = "Asistente")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/GestordePacientes/Controllers/HomeController.cs
using GestordePacientes.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestordePacientes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        // Solo Administradores pueden acceder a MenuAdmin
        [Authorize(Roles = "Administrador")]
        public IActionResult MenuAdmin()
        {
            return View();
        }

        // Solo Asistentes pueden acceder a MenuAssistant
        [Authorize(Roles = "Asistente")]
        public IActionResult MenuAssistant()
        {
            return View();
        }

        public IActionResult Login_Register()
        {
            return View("Login_Register");
        }
        public IActionResult AccessDenied()
        {
            return StatusCode(403); 
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/GestordePacientes/Controllers/MedicosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GestordePacientes.Controllers
{
    public class MedicosController : Controller
    {
        [Authorize(Roles = "Administrador")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApp/GestordePacientes/Controllers/UsuariosController.cs
using GestordePacientes.Core.Application.Services;
using GestordePacientes.Core.Application.ViewModels.User;
using GestordePacientes.Core.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.GestordePacientes.Middlewares;

namespace GestordePacientes.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuariosController : Controller
    {
        private readonly UserService _userService;

        public UsuariosController(UserService userService)
        {
            _userService = userService;
        }

        // Método para eliminar un usuario
        [HttpPost("delete/{id}")]
        public async Task<IActionResult> DeleteUser(int id)
        {
            try
            {
                await _userService.DeleteUserAsync(id);
                return Ok("Usuario eliminado exitosamente.");
            }
            catch (Exception ex)
            {
                return BadRequest("Error al eliminar el usuario: " + ex.Message);
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateUser([FromBody] UserViewModel userViewModel)
        {
            if (userViewModel == null)
                return BadRequest("Los datos del usuario son nulos.");

            // Validación de campos
            if (string.IsNullOrWhiteSpace(userViewModel.Name) ||
            string.IsNullOrWhiteSpace(userViewModel.UserName) ||
            string.IsNullOrWhiteSpace(userViewModel.Email) ||
            string.IsNullOrWhiteSpace(userViewModel.Password) ||
            string.IsNullOrWhiteSpace(userViewModel.ConfirmePassword) ||
            string.IsNullOrWhiteSpace(userViewModel.Rol))
            {
                ViewData["mensaje"] = "Todos los campos deben ser completados.";
                return View(userViewModel);
            }

            if (userViewModel.Password != userViewModel.ConfirmePassword)
            {
                ViewData["mensaje"] = "Las contraseñas no coinciden.";
                return View(userViewModel);
            }

            if (await _userService.CheckUserExists(userViewModel.UserName))
            {
                ViewData["mensaje"] = "El nombre de usuario ya existe. Por favor elige otro.";
                return View(userViewModel);
            }

            TempData["mensaje"] = "Usuario creado exitosamente.";
            return RedirectToAction("Index");

            await _userService.AddAsync(userViewModel);
            return Ok("Usuario creado exitosamente.");
        }

        [HttpGet("check-username")]
        public async Task<IActionResult> CheckUsername(string username)
        {
            var userExists = await _userService.CheckUserExists(username);
            return Ok(userExists);
        }

        public IActionResult Index()
        {
            var users = _userService.GetAllUsersAsync();
            return View(users);
        }
    }
}

WebApp/GestordePacientes/Views/Home/AccesDenied.cshtml
@{
    ViewData["Title"] = "Acceso Denegado";
}

<h1>Acceso Denegado</h1>
<p>No tienes permiso para acceder a esta página.</p>
<a href="@Url.Action("Login_Register", "Shared")">Ir al Login</a>

WebApp/GestordePacientes/Views/Home/MenuAdmin.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema Gestor de Pacientes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #3c5077;
            margin: 0;
        }
        .Admin-screen {
            background-color: #fff;
            border: 2px solid #ccc;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .Admin-screen h1 {
            margin-bottom: 20px;
        }
        .Admin-screen button {
            display: block;
            width: 100%;
            padding: 15px;
            margin: 10px 0;
            font-size: 16px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: white;
            transition: background-color 0.3s;
        }
        .Admin-screen button:hover {
            background-color: #0056b3;
        }

        #salir-button{
            background-color: #dc3545;
        }
        #salir-button:hover {
            background-color: #c82333;
        }
    </style>
</head>
<body>
    <div class="Admin-screen">
        <h1>Sistem Gestor de Pacientes</h1>
        <button onclick="UserManage()">Mantenimiento de Usuarios</button>
        <button onclick="DoctorsManage()">Mantenimiento de Médicos</button>
        <button onclick="LabtestsManage()">Mantenimiento de Pruebas de Laboratorio</button>
        <button type="button" class="btn btn-danger" id="salir-button" onclick="loginRegister()">Atrás</button>
    </div>
 <script>
        function DoctorsManage() {
            window.location.href = '@Url.Action("Index", "Medicos")';
        }
        function UserManage() {
        fetch('@Url.Action("Index", "Usuarios")') 
            .then(response => {
                if (response.status === 403) {
                    alert("No tienes permiso para acceder a esta página.");
                } else if (response.ok) {
                    window.location.href = '@Url.Action("Index", "Usuarios")';
                }
            })
            .catch(error => console.error('Error:', error));
    }
        function LabtestsManage() {
            window.location.href = '@Url.Action("Index", "PruebasLaboratorio")';
        }
        function loginRegister() {
            window.location.href = '@Url.Action("Login_Register", "Shared")';
        }
    </script>
</body>
</html>

WebApp/GestordePacientes/Views/Home/MenuAssistant.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sistema Gestor de Pacientes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #3c5077;
            margin: 0;
        }
        .assistant-screen {
            background-color: #fff;
            border: 2px solid #ccc;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
        .assistant-screen h1 {
            margin-bottom: 20px;
        }
        .assistant-screen button {
            display: block;
            width: 100%;
            padding: 15px;
            margin: 10px 0;
            font-size: 16px;
            cursor: pointer;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: white;
            transition: background-color 0.3s;
        }
        .assistant-screen button:hover {
            background-color: #0056b3;
        }

        #salir-button {
            background-color: #dc3545;
        }

        #salir-button:hover {
                background-color: #c82333;
        }
    </style>
</head>
<body>
    <div class="assistant-screen">
        <h1>Sistem Gestor de Pacientes</h1>
        <button onclick="PatientManage()">Mantenimiento de Pacientes</button>
        <button onclick="DatesManage()">Mantenimiento de Citas</button>
        <button onclick="LabtestsresultsManage()">Mantenimiento de resultados de Pruebas de Laboratorio</button>
        <button type="button" class="btn btn-danger" id="salir-button" onclick="loginRegister()">Atrás</button>
    </div>

    <script>
        function PatientManage() {
            window.location.href = '@Url.Action("Index", "Pacientes")';
        }
        function DatesManage() {
            window.location.href = '@Url.Action("Index", "Citas")';
        }
        function LabtestsresultsManage() {
            window.location.href = '@Url.Action("Index", "ResultadosLaboratorio")';
        }
        function loginRegister() {
            window.location.href = '@Url.Action("Login_Register", "Shared")';
        }
    </script>
</body>
</html>